# Description:
#   Give you an Oblique Strategy to get you un-stuck. Hobbes is a philosopher, at heart.

module.exports = (robot) ->

  // From http://alexplorer.net/music/oblique2.html
  obliques = [
    "(Organic) machinery.",
    "A line has two sides.",
    "A very small object - Its centre.",
    "Look at a very small object, look at its centre.",
    "Abandon normal instruments.",
    "Abandon normal instructions.",
    "Accept advice.",
    "Accretion.",
    "Adding on.",
    "Allow an easement (an easement is the abandonment of a stricture).",
    "Remove a restriction.",
    "Always first steps.",
    "Always give yourself credit for having more than personality.",
    "Are there sections?  Consider transitions.",
    "Ask people to work against their better judgment.",
    "Ask your body.",
    "Assemble some of the instruments in a group and treat the group.",
    "Assemble some of the elements in a group and treat the group.",
    "Balance the consistency principle with the inconsistency principle.",
    "Be dirty.",
    "Be extravagant.",
    "Be less critical more often.",
    "Be less critical.",
    "Breathe more deeply.",
    "Bridges - build - burn.",
    "Cascades.",
    "Change instrument roles.",
    "Change nothing and continue with immaculate consistency.",
    "Change nothing and continue consistently.",
    "Children's voices - speaking - singing.",
    "Children - speaking - singing.",
    "Cluster analysis.",
    "Consider different fading systems.",
    "Consider transitions.",
    "Consult other sources - promising - unpromising.",
    "Convert a melodic element into a rhythmic element.",
    "Courage!",
    "Cut a vital connection.",
    "Decorate, decorate.",
    "Define an area as `safe' and use it as an anchor.",
    "Destroy - nothing - the most important thing.",
    "Discard an axiom.",
    "Disciplined self- indulgence.",
    "Disconnect from desire.",
    "Abandon desire.",
    "Discover the recipes you are using and abandon them.",
    "Discover your formulas and abandon them.",
    "Distorting time.",
    "Distort time.",
    "Do nothing for as long as possible.",
    "Do something boring.",
    "Do something sudden, destructive and unpredictable.",
    "Do the last thing first.",
    "Do the washing up.",
    "Do the words need changing?",
    "Do we need holes?",
    "Don't be afraid of things because they're easy to do.",
    "Don't avoid what is easy.",
    "Don't be frightened of cliches.",
    "Use cliches.",
    "Don't be frightened to display your talents.",
    "Display your talent.",
    "Don't break the silence.",
    "Don't stress one thing more than another.",
    "Emphasize differences.",
    "Emphasize repetitions.",
    "Emphasize the flaws.",
    "Faced with a choice, do both (given by Dieter Rot).",
    "Feed the recording back out of the medium.",
    "Feedback recordings into an acoustic situation.",
    "Fill every beat with something.",
    "Find a safe part and use it as an anchor.",
    "From nothing to more than nothing.",
    "Get your neck massaged.",
    "Ghost echoes.",
    "Give the game away.",
    "Give the name away.",
    "Give way to your worst impulse.",
    "Go outside.  Shut the door.",
    "Shut the door and listen from outside.",
    "Go slowly all the way round the outside.",
    "Go to an extreme, move back to a more comfortable place.",
    "Go to an extreme, come part way back.",
    "Honor thy error as a hidden intention.",
    "Your mistake was a hidden intention.",
    "How would someone else do it?",
    "How would you have done it?",
    "Humanize something free of error.",
    "Make what's perfect more human.",
    "Idiot glee (?)",
    "Imagine the music as a set of disconnected events.",
    "In total darkness, or in a very large room, very quietly.",
    "Infinitesimal gradations.",
    "Intentions - credibility of - nobility of - humility of.",
    "Intentions - nobility of - humility of - credibility of.",
    "Into the impossible.",
    "Is it finished?",
    "Is the intonation correct?",
    "Is the information correct?",
    "Is the style right?",
    "Is the tuning appropriate?",
    "Is there something missing.",
    "Is something missing?",
    "It is quite possible (after all).",
    "It is simply a matter or work.",
    "It is simply a matter of work.",
    "Just carry on.",
    "Left channel, right channel, center channel.",
    "Listen in total darkness, or in a very large room, very quietly.",
    "Listen to the quiet voice.",
    "Look at the order in which you do things.",
    "Look closely at the most embarrassing details & amplify them.",
    "Lost in useless territory.",
    "Lowest common denominator check - single beat - single note - single riff.",
    "Lowest common denominator.",
    "Magnify the most difficult details.",
    "Make a blank valuable by putting it in an exquisite frame.",
    "Make a sudden, destructive unpredictable action; incorporate.",
    "Make an exhaustive list of everything you might do and do the last thing on the list.",
    "Make it more sensual.",
    "Mechanicalize something idiosyncratic.",
    "Mute and continue.",
    "Not building a wall but making a brick.",
    "Once the search is in progress, something will be found.",
    "Once the search has begun, something will be found.",
    "Only a part, not the whole.",
    "Only one element of each kind.",
    "Overtly resist change.",
    "Openly resist change.",
    "Pae White's non-blank graphic metacard.",
    "Put in earplugs.",
    "Question the heroic approach.",
    "Question the heroic.",
    "Remember those quiet evenings.",
    "Remember quiet evenings.",
    "Remove ambiguities and convert to specifics.",
    "Change ambiguities to specifics.",
    "Remove specifics and convert to ambiguities.",
    "Change specifics to ambiguities.",
    "Repetition is a form of change.",
    "Retrace your steps.",
    "Revaluation (a warm feeling).",
    "Reevaluation (a warm feeling).",
    "Reverse.",
    "Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them straight into his lap).",
    "Simple subtraction.",
    "Simply a matter of work.",
    "Slow preparation, fast execution.",
    "Spectrum analysis.",
    "State the problem in words as clearly as possible.",
    "State the problem as clearly as possible.",
    "Take a break.",
    "Take away the elements in order of apparent non-importance.",
    "Take away the important parts.",
    "Tape your mouth. (given by Ritva Saarikko)",
    "The inconsistency principle.",
    "The most important thing is the thing most easily forgotten.",
    "The most easily forgotten thing is the most important.",
    "The tape is now the music.",
    "Think - inside the work - outside the work.",
    "Think of the radio.",
    "Tidy up.",
    "Towards the insignificant.",
    "Move towards the unimportant.",
    "Trust in the you of now.",
    "Try faking it. (from Stewart Brand)",
    "Turn it upside down.",
    "Twist the spine.",
    "Use an old idea.",
    "Use an unacceptable color.",
    "Use fewer notes.",
    "Use filters.",
    "Use something nearby as a model.",
    "Use 'unqualified' people.",
    "Voice your suspicions.",
    "Water.",
    "What are the sections sections of?  Imagine a caterpillar moving.",
    "Imagine the music as a moving chain or caterpillar.",
    "What are you really thinking about just now? Incorporate.",
    "What are you really thinking about just now?",
    "What context would look right?",
    "What is the reality of the situation?",
    "What is the simplest solution?",
    "What mistakes did you make last time?",
    "What to increase? What to reduce? What to maintain?",
    "What were you really thinking about just now?",
    "What would your closest friend do?",
    "What wouldn't you do?",
    "When is it for?",
    "Where is the edge?",
    "Which parts can be grouped?",
    "Work at a different speed.",
    "Would anybody want it?",
    "Would anyone want it?",
    "You are an engineer.",
    "You can only make one dot at a time.",
    "You don't have to be ashamed of using your own ideas."
  ]

  robot.respond /I'm stuck/i, (msg) ->
    msg.send msg.random obliques
